<?php

namespace AppBundle\Repository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserId($id)
    {
        return $this->createQueryBuilder('participant')
            ->where('participant.userId = :userId')
            ->setParameter('userId', $id)
            ->getQuery()
            ->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }

    public function findByIds($ids)
    {
        return $this->createQueryBuilder('participant')
            ->where('participant.id = :id')
            ->setParameter('id', $ids)
            ->getQuery()
            ->getResult();
    }
}
