# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        webservices:
            id: AppBundle\Security\User\WebserviceUserProvider
        in_memory:
            memory: ~
   # encoders:
    #    AppBundle\Security\User\WebserviceUser: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - AppBundle\Security\User\Authenticator

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
